pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // This runs TestNG tests using your root-level testng.xml
                sh 'mvn clean test'
            }
        }
    }

    post {
        always {
            // Collects test result XMLs generated by Maven Surefire
            junit 'target/surefire-reports/*.xml'

            // Optional: archives HTML reports from test-output folder
            archiveArtifacts artifacts: 'test-output/**/*.html', fingerprint: true
        }
    }
}
