//package com.group3.CRMtests;
//
//
//import com.group3.CRMbasics.BaseTest;
//import com.group3.CRMlistners.ExtentManager;
//import com.group3.CRMlogs.Logs;
//import com.group3.CRMpages.CreateUserPage;
//
//import java.util.List;
//import java.util.concurrent.TimeUnit;
//
//import org.openqa.selenium.By;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.PageFactory;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.testng.Assert;
//import org.testng.annotations.Test;
//
//import io.github.bonigarcia.wdm.WebDriverManager;
//
//public class CreateUserTest extends BaseTest {
//
//	//CreateUserTest userPage;
//	WebDriver driver;//=userPage.getDriver();
//	CreateUserPage userPage;
//
//	public void commonfunctionality() throws InterruptedException {
//		driver=getDriver();
//		userPage= new CreateUserPage(driver);
//		Actions actions= new Actions(driver);
//		Thread.sleep(3000);
//		//adminMenu=userPage.getAdminMenu();
//		//river.findElement(By.xpath("//div[@class='nav-link' and contains(., 'Admin Console')]"));
//		actions.moveToElement(userPage.getAdminMenu()).perform();
//		//actions.moveToElement(adminMenu).perform();
//		WebElement createUserLink=userPage.getCreateUserLink();
//		//iver.findElement(By.xpath("//div[@class='dropdown-item' and text()='Create User']")); 
//		actions.moveToElement(createUserLink).click().perform();
//	}
//	public void commonfunctionality1() throws InterruptedException {
//		driver=getDriver();
//		userPage= new CreateUserPage(driver);
//		Actions actions= new Actions(driver);
//		Thread.sleep(3000);
//		WebElement adminMenu=userPage.getAdminMenu();
//		//river.findElement(By.xpath("//div[@class='nav-link' and contains(., 'Admin Console')]"));
//		actions.moveToElement(adminMenu).perform();
//		WebElement getViewUser=driver.findElement(By.xpath("//div[@class='dropdown-item' and text()='View Users']"));
//		//getViewUser.click();
//		WebElement createUserLink=userPage.getCreateUserLink();
//		actions.moveToElement(getViewUser).click().perform();
//	}
//
//	@Test
//	public void testuniqueIdGenerated() throws InterruptedException {
//		commonfunctionality1();
//		//driver.find//div[@class='dropdown-item' and text()='View Users']
//
//		List<WebElement> rowsBefore1=driver.findElements(By.xpath("//table[@class='table table-striped table-hover']//tbody//tr"));
//		int initialRowCount1 = rowsBefore1.size();
//		System.out.println("count is"+initialRowCount1);
//		commonfunctionality();
//		commonfunctionality();
//		String username="gtffghnn";
//		String username1="guuyjjnmnm";
//		userPage.createUser(username1, "6907273291", "cmoie@stmail.com",username,"fgghgj");
//		Thread.sleep(3000);
//		WebElement firstCell = driver.findElement(By.xpath("//table[@class='table table-striped table-hover']//tbody/tr[1]/td[1]"));
//		String value = firstCell.getText();
//		System.out.println("First value in the table: " + value);
//		List<WebElement> rowsAfter=driver.findElements(By.xpath("//table[@class='table table-striped table-hover']//tbody//tr"));
//
//		WebElement newRow =rowsAfter.get(rowsAfter.size() - 1);
//		String autoGeneratedId = newRow.findElement(By.xpath("./td[1]")).getText(); 
//		System.out.println("autoGenerated ID: " + autoGeneratedId);
//	}
//	@Test
//	public void testCreateUserValidData() throws Throwable {
//
//
//		commonfunctionality();
//		String username="gjuonn";
//		String username1="gjjn";
//		userPage.createUser(username1, "6989273291", "cybbie@stmail.com",username,"fgghgj");
//		Thread.sleep(3000);
//		WebElement alertMsg = userPage.getAlertMsg();;
//		String alertText = alertMsg.getText();
//		System.out.println("Alert Message: " + alertText);	
//		//Assert.assertEquals(alertText, "User "+username1+" Successfully Added");
//		// Add assertion here based on success message or redirection
//
//	}
//	@Test
//	public void userNameFieldBlankAlert() throws InterruptedException
//	{
//		// Invalid, only one word
//		commonfunctionality();
//		WebElement fullNameInput = driver.findElement(By.name("empName"));
//		fullNameInput.sendKeys(""); 
//		userPage.clickSubmit();
//		JavascriptExecutor js = (JavascriptExecutor) driver;
//		String patternMessage = (String) js.executeScript(
//				"return arguments[0].validationMessage;", fullNameInput);
//
//		System.out.println("Pattern Validation Message: " + patternMessage);
//
//		Assert.assertEquals(patternMessage, "Please fill out this field.");
//		Logs.info("checkuserNamefieldEmpty Alrt message");
//		ExtentManager.logTestInfo("checkuserNamefieldEmpty Alrt message");
//	}
//	@Test
//	public void userMobileldBlankAlert() throws InterruptedException
//	{
//		// Invalid, only one word
//		commonfunctionality();
//		userPage.enterFirstName("ghghgj");
//		userPage.entermobileNumber("");
//		userPage.clickSubmit();
//		JavascriptExecutor js = (JavascriptExecutor) driver;
//		String patternMessage = (String) js.executeScript(
//				"return arguments[0].validationMessage;",userPage.getEmailInput());
//
//		System.out.println("Pattern Validation Message: " + patternMessage);
//
//		Thread.sleep(3000);
//	}
//		@Test
//	public void userEmailBlankAlert() throws InterruptedException
//	{
//		// Invalid, only one word
//		commonfunctionality();
//		WebElement fullNameInput = driver.findElement(By.name("empName"));
//		fullNameInput.sendKeys("");
//		userPage.entermobileNumber("123abc!@#");
//		 String actualValue = userPage.getMobileNumber().getAttribute("value");
//	        System.out.println("Final value in field: " + actualValue);
//		userPage.enterEmail("");
//		userPage.clickSubmit();
//		
//		  JavascriptExecutor js = (JavascriptExecutor) driver; String patternMessage =
//		  (String) js.executeScript( "return arguments[0].validationMessage;",
//		  userPage.getMobileNumber());
//		 
//		System.out.println("Pattern Validation Message: " + patternMessage);
//
//		//mobileField.sendKeys("123abc!@#");
//	}
//	//@Test
//	public void userUsernameBlankAlert() throws InterruptedException
//	{
//		// Invalid, only one word
//		commonfunctionality();
//		WebElement fullNameInput = driver.findElement(By.name("empName"));
//		fullNameInput.sendKeys("uyjhkjhjk"); 
//		userPage.entermobileNumber("1233444556");
//		userPage.enterEmail("asd@g.com");
//		userPage.enterUserName("");
//		userPage.clickSubmit();
//		JavascriptExecutor js = (JavascriptExecutor) driver;
//		String patternMessage = (String) js.executeScript(
//				"return arguments[0].validationMessage;", userPage.getUserName());
//
//		System.out.println("Pattern Validation Message: " + patternMessage);
//
//
//	}
//	//@Test
//	public void userPasswordBlankAlert() throws InterruptedException
//	{
//		// Invalid, only one word
//		commonfunctionality();
//		WebElement fullNameInput = driver.findElement(By.name("empName"));
//		fullNameInput.sendKeys("uyjhkjk"); 
//		userPage.entermobileNumber("1633444556");
//		userPage.enterEmail("asd@g1.com"); 
//		userPage.enterUserName("hjghjh");
//		userPage.enterPassword("");
//		userPage.clickSubmit();
//		JavascriptExecutor js = (JavascriptExecutor) driver;
//		String patternMessage = (String) js.executeScript(
//				"return arguments[0].validationMessage;", userPage.getPasswordInput());
//
//		System.out.println("Pattern Validation Message: " + patternMessage);
//
//
//	}
//
//
//}
